### ISSUE TITLE
[FATAL] key file is in error format

### ISSUE THREAD

**Issue by countstarlight** [xczh/jetserver#3]
I download activation code from https://account.jetbrains.com/licenses and use:
```shell
make
cd build
./jetserver -key jetbrains_key.txt
```
But meet:
```
2018/04/29 12:18:32 [INFO] retrieval product info from jetbrains service ...
2018/04/29 12:18:34 [INFO] retrieval product info ok
Jetbrains License Server v1.2
Date: 2018/04/29 11:18:33
Build: go1.10.1 linux/amd64
Git Hash: beb1620d05fa324695df76e81240daa30ef7e8f4

2018/04/29 12:18:34 [FATAL] key file is in error format
```

**Comment by xczh** [comment]
This is not for the official license key

**Comment by countstarlight** [comment]
I can't understand, maybe you can send me a sample file, my email: countstarlight@gmail.com
Thank you.

**Comment by xczh** [comment]
If you have an official license, it is recommended that you find the official documentation to understand how to deploy a license server. This repo is for the users who do not have an official license but want to deploy a license server. (yeah, maybe a crack?)

**Comment by countstarlight** [comment]
I know, thank you:)
